backbone_config:
  model: 'BackboneNB201'
  spec: None
  stem_out_channels: 16
  num_stacks: 3
  num_modules_per_stack: 3
  num_labels: 10

head_config:
  model: 'HeadEmptyMid'
  loss_type: 'mseloss'
  out_channel: [128,128,128]
  last_channel: [128,128,128]
  batch_size: 16
  width: 8
  height: 8
  feature_list: [['wave_h'], ['wave_h'], ['wave_h']]

barrier_config:
  model: 'SimpleBarrier'

generator_config:
  model: 'FeatureGeneratorNotrain'
  # load_from_save: 'data/saved_models/ckpt.pth'
  # state_dict_name: 'net'
arch_config:
  train_archs_accs: './data/nb201/tinyimagenet.json'
  eval_archs_accs: './data/nb201/tinyimagenet.json'

dataset_config:
  batch_size: 16
  
optim_g_config:
  optim: 'sgd'
  lr: 1.0e-3
  momentum: 0.9
  weight_decay: 0.00004

optim_a_config:
  optim: 'sgd'
  lr: 1.2
  momentum: 0.9
  weight_decay: 0.00004

train_config:
  total_pairs: 200
  g_iters: 10
  a_iters: 10
  eval_interval: 10
  eval_show_metric_interval: 20
  rank_metric: 'spearmanr'
  rank_reverse: True
  max_eval_sample: 2500
  train_sample: 20
  mac_mode: 'macs'
  # init_net: ['kaiming', 'kaiming']
  # init_barrier:  ['kaiming', 'kaiming']

