backbone_config:
  model: 'BackboneNDS'
  spec: None
  stem_out_channels: 16
  num_stacks: 3
  num_modules_per_stack: 3
  num_labels: 10
  NDS: None
  arch: None
  search_space: 'ResNeXt-A'
  datapath: './data/download_data/nds_data/'

head_config:
  model: 'HeadEmptyNAS'
  loss_type: 'mseloss'
  batch_size: 16
  width: 8
  height: 8
  search_space: 'resnexta'
  out_channel: [512]
  last_channel: [64]
  feature_list: [['net', 'wave_h'], ['net', 'wave_h'], ['net', 'wave_h']]
  alpha: 0.1
  index: [1,1,1]
  barrier_index: [1,1,1]
  levels: 1.0

nas_config:
  lrs: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5]
  alphas: [-0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5]
  network:
    branch_number: [1, 2, 3]
    barrier_indexes: [0, 1, 2]
    indexes: [0, 1, 2]
    channels: [16, 32, 64, 128, 256, 512]
  features: ['net', 'wave_l', 'wave_m', 'wave_h', 'dot']
  levels: [0.5, 1, 1.5, 2]
  cnn_inits: ['xavier_uniform', 'xavier_normal', 'kaiming_uniform', 'kaiming_normal']
  barrier_inits: ['xavier_uniform', 'xavier_normal', 'kaiming_uniform', 'kaiming_normal']
ea_config:
  mutate_ratio: 0.2
  p_size: 40
  e_size: 10

barrier_config:
  model: 'BarrierNAS'

generator_config:
  model: 'FeatureGeneratorNotrain'
  # load_from_save: 'data/saved_models/ckpt.pth'
  # state_dict_name: 'net'
arch_config:
  train_archs_accs: './data/nb201/cifar10valid.json'
  eval_archs_accs: './data/nb201/cifar10valid.json'

dataset_config:
  batch_size: 16
  
optim_g_config:
  optim: 'sgd'
  lr: 1.0e-3
  momentum: 0.9
  weight_decay: 0.00004

optim_a_config:
  optim: 'sgd'
  lr: 1.2
  momentum: 0.9
  weight_decay: 0.00004

train_config:
  total_pairs: 200
  g_iters: 10
  a_iters: 10
  eval_interval: 10
  eval_show_metric_interval: 20
  rank_metric: 'spearmanr'
  rank_reverse: True
  mac_mode: 'loss_macs'
  max_eval_sample: 2500
  train_sample: 20


