backbone_config:
  model: 'BackboneNB101'
  spec: None
  stem_out_channels: 32
  num_stacks: 3
  num_modules_per_stack: 3
  num_labels: 10

head_config:
  model: 'HeadNB101'
  loss_type: 'celoss'
  out_channel: 128
  last_channel: 64