backbone_config:
  model: 'BackboneNDS'
  spec: None
  stem_out_channels: 128
  num_stacks: 3
  num_modules_per_stack: 3
  num_labels: 10
  NDS: None
  arch: None
  search_space: 'ResNet'
  datapath: './data/download_data/nds_data/'

nas_config:
  channels: [16,32,64,128,256,512]
  combos: [['dot'], ['sin'], ['net'], ['dot', 'sin'], ['sin', 'net'], ['dot', 'net'], ['dot', 'sin', 'net']]
  network: 
    layer: 4
    choices: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  lrs: [1.0, 1.2, 1.4, 1.6, 1.8, 2.0]


head_config:
  model: 'HeadEmptyMidNDSNAS'
  loss_type: 'mseloss'
  out_channel: 512
  last_channel: 128
  index: None
  combo: None
  batch_size: 16
  width: 8
  height: 8

generator_config:
  model: 'SiamGeneratorNAS'
  # load_from_save: 'data/saved_models/ckpt.pth'
  # state_dict_name: 'net'
arch_config:
  train_archs_accs: './data/nb101/nasbench1_20.json'
  eval_archs_accs: './data/nb101/nasbench1_2500.json'

dataset_config:
  batch_size: 16
  
optim_g_config:
  optim: 'sgd'
  lr: 1.0e-3
  momentum: 0.9
  weight_decay: 0.00004

optim_a_config:
  optim: 'sgd'
  lr: 1.0
  momentum: 0.9
  weight_decay: 0.00004

train_config:
  total_pairs: 200
  g_iters: 10
  a_iters: 10
  eval_interval: 10
  eval_show_metric_interval: 20
  rank_metric: 'spearmanr'
  rank_reverse: True
  max_eval_sample: 1000
  train_sample: 20

